pipeline:
  name: IaC Scan
  identifier: IaC_Scan
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Gitrepos
        repoName: kaimonkey
        build: <+input>
  stages:
    - stage:
        name: IaC_Scan
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Plugin
                  name: AccuKnox_IaC
                  identifier: Plugin_1
                  spec:
                    connectorRef: My_connector
                    image: accuknox/harness-iac-plugin:v1
                    settings:
                      repo_id: https://harness.com/user/demo
                      branch: main
                      endpoint: 174.138.123.212:5000
                      tenant_id: "2"
                      label: IAC
                      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyMzgyOTI0LCJqdGkiOiJjODY1Njc3OTdiM2U0MjgxYjFlYmY2YTZjZGVjNTU1NiIsImlzcyI6ImNzcG0uaW50ZXJuYWwudGVzdC5jb20ifQ.dymsQjHYUsk-mMfLLCTmFbNtth790F-Y6ODxqzqMyUqCSBTPdc1U7FeMNcOcOvc417qeFVA9eJjpmMfdxfgElQW3IGqo2TupU44zr99ZW00LJ5c-PvAHYyYjrFoyA8vLpUouOGlf0CQ4h3E0E9vslY19_IcBQWRjUYrKOLkm16WzawmSLFMgUgDI5IDf-CHsTRfQ83xNfNuxL5asN9yEkHmWkJAbpIYPjXBeqc1P8qc6LNMBctvHiZn_VewzfuuedEQTbIfUB0iXUJnL0mZwXOc-NHthQ5GYc_GS_sPP6r9VPdbeVVpAI4fk64OeVllgXRBDO54MIQiQ1B1d-L7DVA
          caching:
            enabled: false
            paths: []
  allowStageExecutions: true
